principles = [
    "Multiply and replenish the earth",
    "Sex only used between a husband and wife who are married to each other",
    "Love your spouse",
    "Love your children",
    "Care for you spouse",
    "Care for your children",
    "Rear your children in love",
    "Rear your children in righteousness",
    "Provide for your children's physical needs",
    "Provide for your children's spiritual needs",
    "Teach your children to love one another",
    "Teach your children to serve one another",
    "Teach your children to keep God's commandments",
    "Teach your children to be law-abiding citizens wherever they live",
    "Bear children only within matrimony",
    "Make sure your children are raised with a father and a mother",
    "Make sure your children are raised with by parents that owner marital vows with complete fidelity",
    "Use the teachings of the Lord Jesus Christ as the foundation for family life",
    "Establish and maintain your marriage on faith",
    "Establish and maintain your family on faith",
    "Establish and maintain your marriage on prayer",
    "Establish and maintain your family on prayer",
    "Establish and maintain your marriage on repentance",
    "Establish and maintain your family on repentance",
    "Establish and maintain your marriage on forgivenes",
    "Establish and maintain your family on forgiveness",
    "Establish and maintain your marriage on respect",
    "Establish and maintain your family on respect",
    "Establish and maintain your marriage on love",
    "Establish and maintain your family on love",
    "Establish and maintain your marriage on compassion",
    "Establish and maintain your family on compassion",
    "Establish and maintain your marriage on work",
    "Establish and maintain your family on work",
    "Establish and maintain your marriage on wholesome recreational activities",
    "Establish and maintain your family on wholesome recreational activities",
    "Have the husband/father preside over his family in love",
    "Have the husband/father preside over his family in righteousness",
    "Have the husband/father provide the necessities of life for his family",
    "Have the husband/father provide the necessities of protection for his family",
    "Have the wife/mother nurture her family's children",
    "Have the father and mother help one another in these sacred responsibilities",
    "Have the father and mother help one another in these sacred responsibilities as equal partners"
]